-- This file contain the drop index statements (on SQL Express) for the Nippon File Transfer project @ Dualog.

DROP INDEX "ftdui_transferjob"."ftdui_transferjob_default_source_id";
DROP INDEX "ftdui_source"."ftdui_source_client_id";
DROP INDEX "ftdui_source"."ftdui_source_folder_id";
DROP INDEX "ftdui_source"."ftdui_source_job_id";
DROP INDEX "ftdui_destination"."ftdui_destination_client_id";
DROP INDEX "ftdui_destination"."ftdui_destination_folder_id";
DROP INDEX "ftdui_destination"."ftdui_destination_job_id";
DROP INDEX "ftdui_client"."ftdui_client_key_id";






